defaults: # for loading the default.yaml config
  - model: ???
  - data: ???

  - visualization: default
  - training: default
  - debugging: default
  - sota # Contains current SOTA results on different datasets (extracted from papers !).

job_name: benchmark # prefix name for saving the experiment file.
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
update_bn_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: False
eval_frequency: 1
model_name: "${get_filename: ${hydra:runtime.choices.model}}"

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False