# @package training
defaults:
  - /training/default
  - override optim/optimizer: SGD

epochs: 500
num_workers: 4
batch_size: 12

optim:
  base_lr: 0.1
  weight_decay: 1e-4
  
  momentum: 0.9
  dampening: 0.1
  
  bn_momentum: 0.1
  bn_decay: 0.2
  bn_decay_step: 200
  bn_clip: 2e-2

wandb:
  project: scannet
  notes: "Minkowski baseline"
  name: "Res16UNet34C"
  config:
    grid_size: ${data.first_subsampling}
    model_name: ${model_name}

# Ref: https://github.com/chrischoy/SpatioTemporalSegmentation/blob/master/config.py
