# @package training
defaults:
  - /training/default
  - override optim/optimizer: Adam

epochs: 200
num_workers: 4
batch_size: 4

optim:
  base_lr: 1e-3
  
  bn_momentum: 0.5
  bn_decay: 0.5
  bn_decay_step: 20
  bn_clip: 1e-2

wandb:
  project: scannet_object_detection
  notes: "Corrected box prediction"
  name: VoteNet
