# @package training
defaults:
  - /training/default
  - override optim/optimizer: SGD
  - override optim/bn_scheduler: 

epochs: 200
num_workers: 6
batch_size: 4

optim:
  base_lr: 1e-1

  momentum: 0.8
  weight_decay: 1e-4

  lr_scheduler:
    gamma: 0.99

wandb:
  project: registration
