# @package training
defaults:
  - /training/default
  - override optim/optimizer: SGD

epochs: 300
num_workers: 4
batch_size: 8

optim:
  base_lr: 0.1
  grad_clip: 100

  weight_decay: 1e-4
  
  bn_momentum: 0.02
  bn_decay: 1
  bn_decay_step: 1000
  bn_clip: 1e-2

wandb:
  project: s3dis-benchmark
  notes: "Minkowski baseline"
  name: "Res16UNet34C "
  config:
    fold: ${data.fold}
    model_name: ${model_name}
