# @package training
defaults:
  - /training/default
  - override optim/optimizer: SGD

epochs: 300
num_workers: 2
batch_size: 8

optim:
  base_lr: 0.01
  grad_clip: 100
  
  momentum: 0.98
  weight_decay: 1e-3
  
  bn_momentum: 0.02
  bn_decay: 0.9
  bn_decay_step: 1000
  bn_clip: 1e-2

wandb:
  project: s3dis-benchmark
  notes: "rsconv baseline"
  name: "rsconv"
